### ISSUE TITLE
Add range checks

### ISSUE THREAD

**Issue by eschnett** [mbauman/IntSets.jl#2]
Some of the `IntSet` routines take integers as arguments, e.g. `push` and `pop`, and also internal routines like `_ensureroom!`. Many of these routines have problems with integer overflow if called with an `Int32` argument. This is a problem in practice; see e.g. #8570 where some tried to create an `IntSet` with 2^32+1 elements.

**Comment by mbauman** [comment]
This should have been addressed in my recent updates.
